default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9  # v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: no-commit-to-branch
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 193ee766ca496871f93621d6b58d57a6564ff81b  # 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 7f91e1434e195a0121bc66bd50426f2140b5f862  # v2.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
